caog_horarios_homepage:
    path:     /
    defaults: { _controller: CaogHorariosBundle:Default:index }
# usuario
caog_horarios_user_register:
    path: /user/register
    defaults: { _controller: CaogHorariosBundle:Usuario:registrar}
caog_horarios_user_list:
    path: /user/list
    defaults: { _controller: CaogHorariosBundle:Usuario:list}
caog_horarios_user_timetable:
    path: /user/timetable/{id}
    defaults: { _controller: CaogHorariosBundle:Usuario:timetable, id: 0}
# Usuario->Actividad:
caog_horarios_usuario_actividad_register:
    path: /user/actividad/register/{id}
    defaults: { _controller: CaogHorariosBundle:ActividadUsuario:registrar,id: 0}

caog_horarios_usuario_actividad_list:
    path: /user/actividad/list/{id}
    defaults: { _controller: CaogHorariosBundle:ActividadUsuario:list,id: 0}

caog_horarios_usuario_actividad_vincular:
    path: /usuario/actividad/vincular/{id}
    defaults: { _controller: CaogHorariosBundle:ActividadUsuario:vincular, id: 0}
    
caog_horarios_usuario_franjas_publicas_crear:
    path: /user/franjas/publicas/crear/{idUser}
    defaults: { _controller: CaogHorariosBundle:ActividadFranja:create, idUser: 0}
       
# Empresa
caog_horarios_empresa_register:
    path: /empresa/register
    defaults: { _controller: CaogHorariosBundle:Empresa:registrar}
caog_horarios_empresa_list:
    path: /empresa/list
    defaults: { _controller: CaogHorariosBundle:Empresa:list}
# Empresa->Actividaa
caog_horarios_empresa_actividad_register:
    path: /empresa/actividad/register/{idEmpresa}
    defaults: { _controller: CaogHorariosBundle:ActividadEmpresa:registrar}
caog_horarios_empresa_actividad_getActividadEmpresaAjax:
    path: /empresa/actividad/getActividadEmpresaAjax
    defaults: { _controller: CaogHorariosBundle:ActividadEmpresa:getActividadEmpresaAjax}
caog_horarios_empresa_actividad_getActividadEmpresa:
    path: /empresa/actividad/getActividadEmpresa
    defaults: { _controller: CaogHorariosBundle:ActividadEmpresa:getActividadEmpresa}
    
caog_horarios_empresa_actividad_list:
    path: /empresa/actividad/list/{idEmpresa}
    defaults: { _controller: CaogHorariosBundle:ActividadEmpresa:list, idEmpresa: 0}
    
caog_horarios_empresa_actividad_vincular:
    path: /empresa/actividad/vincular/{id}
    defaults: { _controller: CaogHorariosBundle:ActividadFranja:vincular, id: 0}
    
 
