caog_horarios_homepage:
    path:     /
    defaults: { _controller: CaogHorariosBundle:Default:index }
caog_horarios_user_register:
    path: /user/register
    defaults: { _controller: CaogHorariosBundle:Usuario:registrar}
caog_horarios_user_list:
    path: /user/list
    defaults: { _controller: CaogHorariosBundle:Usuario:list}
caog_horarios_empresa_register:
    path: /empresa/register
    defaults: { _controller: CaogHorariosBundle:Empresa:registrar}
caog_horarios_empresa_list:
    path: /empresa/list
    defaults: { _controller: CaogHorariosBundle:Empresa:list}
